package com.abtalks.interview.service;

import com.abtalks.interview.domain.Evaluation;
import com.abtalks.interview.domain.Feedback;
import com.abtalks.interview.domain.InterviewSession;
import com.abtalks.interview.planner.CoverageManager;
import com.abtalks.interview.prompt.FeedbackPromptBuilder;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;

@Service
public class FeedbackService {

    private final CoverageManager coverageManager;

    private final FeedbackPromptBuilder promptBuilder;

    private final LLMService llmService;

    private final ObjectMapper objectMapper;

    public FeedbackService(
            CoverageManager coverageManager, FeedbackPromptBuilder promptBuilder,
            LLMService llmService,
            ObjectMapper objectMapper) {
        this.coverageManager = coverageManager;

        this.promptBuilder = promptBuilder;
        this.llmService = llmService;
        this.objectMapper = objectMapper;
    }

    public Feedback generateFeedback(
            InterviewSession session) {

        String prompt =
                promptBuilder.buildPrompt(session);

        String response =
                llmService.generateJson(prompt);

        try {

            Feedback feedback =
                    objectMapper.readValue(
                            cleanJson(response),
                            Feedback.class
                    );

            /*
             * Deterministic metrics.
             * These must NOT be generated by the LLM.
             */

            double overallScore =
                    session.getEvaluations()
                            .stream()
                            .mapToDouble(Evaluation::getScore)
                            .average()
                            .orElse(0.0);

            int questionsAsked =
                    session.getProgress()
                            .getQuestionCount();

            int curriculumDaysCovered =
                    coverageManager
                            .getCoveredDays(session)
                            .size();

            feedback.setOverallScore(
                    Math.round(overallScore * 10.0) / 10.0
            );

            feedback.setQuestionsAsked(
                    questionsAsked
            );

            feedback.setCurriculumDaysCovered(
                    curriculumDaysCovered
            );

            return feedback;

        } catch (Exception e) {

            throw new IllegalStateException(
                    "Unable to parse final interview feedback",
                    e
            );
        }
    }

    private String cleanJson(String response) {

        if (response == null || response.isBlank()) {

            throw new IllegalStateException(
                    "LLM returned empty feedback"
            );
        }

        String cleaned = response.trim();

        if (cleaned.startsWith("```json")) {
            cleaned = cleaned.substring(7);
        }

        if (cleaned.startsWith("```")) {
            cleaned = cleaned.substring(3);
        }

        if (cleaned.endsWith("```")) {
            cleaned = cleaned.substring(
                    0,
                    cleaned.length() - 3
            );
        }

        return cleaned.trim();
    }
}